name: PharmAI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # Aquí puedes incluir dependencias conda que realmente necesites. Si no las requieres, omítelas.
  - pip:
      - accelerate==1.6.0
      - altair==5.5.0
      - attrs==25.3.0
      - bitsandbytes==0.42.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cryptography==44.0.2
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - faiss-cpu==1.10.0
      - filelock==3.18.0
      - fonttools==4.56.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.1
      - idna==3.10
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - narwhals==1.33.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==2.2.3
      - openpyxl==3.1.5
      - pandas==2.2.3
      - pdfminer==20191125
      - pdfminer-six==20240706
      - pillow==11.2.0
      - pluggy==1.5.0
      - protobuf==5.29.4
      - pyarrow==19.0.1
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydeck==0.9.1
      - pyparsing==3.2.3
      - pypdf2==3.0.1
      - pytest==8.3.5
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
