name: PharmAI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyzmq
  - ipykernel
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - tornado
  - traitlets
  - typing_extensions
  - wheel
  - zlib
  - sqlite
  - tk
  - pip:
      - certifi
      - charset-normalizer
      - idna
      - pypdf2
      - pytz
      - requests
      - tzdata
      - urllib3
